#ifndef CTS_H
#define CTS_H

#include "common.h"

#define MAX_SEQUENCE  65536
#define MIN_HEARTBEAT 30
#define MAX_HEARTBEAT 600

#define UPGRADE_EOS    "upgrade eos"
#define INSTALL_PLUGIN "install plugin"

typedef enum cts_code {
    CODE_ID_MISMATCH                 = 100,
    CODE_HEARTBEAT                   = 1000,
    CODE_HEARTBEAT_ACK               = 1001,
    CODE_AUTH                        = 1002,
    CODE_AUTH_ACK                    = 1003,
    CODE_CONNECT                     = 1004,
    CODE_CONNECT_ACK                 = 1005,
    CODE_INFO                        = 1006,
    CODE_INFO_ACK                    = 1007,
    CODE_QUERY                       = 1008,
    CODE_QUERY_ACK                   = 1009,
    CODE_REBOOT                      = 1010,
    CODE_REBOOT_ACK                  = 1011,
    CODE_RESET                       = 1012,
    CODE_RESET_ACK                   = 1013,
    CODE_SAVE                        = 1014,
    CODE_SAVE_ACK                    = 1015,
    CODE_UPGRADE                     = 1016,
    CODE_UPGRADE_ACK                 = 1017,
    CODE_SLEEP                       = 1018,
    CODE_SLEEP_ACK                   = 1019,
    CODE_SET_AP                      = 1020,
    CODE_SET_AP_ACK                  = 1021,
    CODE_SET_NETWORK                 = 1022,
    CODE_SET_NETWORK_ACK             = 1023,
    CODE_SET_PPPOE                   = 1024,
    CODE_SET_PPPOE_ACK               = 1025,
    CODE_BIND_AP                     = 1028,
    CODE_BIND_AP_ACK                 = 1029,
    CODE_SET_WIFI                    = 1030,
    CODE_SET_WIFI_ACK                = 1031,
    CODE_FAULT_DETECT                = 1032,
    CODE_FAULT_DETECT_ACK            = 1033,
    CODE_SET_WIFI_SWITCH             = 1034,
    CODE_SET_WIFI_SWITCH_ACK         = 1035,
    CODE_SET_WIFI_WAN                = 1038,
    CODE_SET_WIFI_WAN_ACK            = 1039,
    CODE_ALARM                       = 1040,
    CODE_ALARM_ACK                   = 1041,
    CODE_FAULT                       = 1042,
    CODE_FAULT_ACK                   = 1043,
    CODE_OFFLINE                     = 1044,
    CODE_OFFLINE_ACK                 = 1045,
    CODE_ONLINE                      = 1046,
    CODE_ONLINE_ACK                  = 1047,
    CODE_SET_REPORT                  = 1048,
    CODE_SET_REPORT_ACK              = 1049,
    CODE_CHANGED                     = 1050,
    CODE_CHANGED_ACK                 = 1051,
    CODE_REPORT                      = 1052,
    CODE_REPORT_ACK                  = 1053,
    CODE_SET_AI_WIFI                 = 1054,
    CODE_SET_AI_WIFI_ACK             = 1055,
    CODE_SET_ELINK_SWITCH            = 1056,
    CODE_SET_ELINK_SWITCH_ACK        = 1057,
    CODE_SET_BLACKLIST               = 1058,
    CODE_SET_BLACKLIST_ACK           = 1059,
    CODE_SET_WIFI_SYNC               = 1060,
    CODE_SET_WIFI_SYNC_ACK           = 1061,
    CODE_PLUGIN_CMD                  = 1062,
    CODE_PLUGIN_CMD_ACK              = 1063,
    CODE_SET_MESH_SWITCH             = 1064,
    CODE_SET_MESH_SWITCH_ACK         = 1065,
    CODE_SET_ELINK_SYNC              = 1066,
    CODE_SET_ELINK_SYNC_ACK          = 1067,
    CODE_UPGRADE_EOS                 = 1068,
    CODE_UPGRADE_EOS_ACK             = 1069,
    CODE_AUTHED_DEV_QUERY            = 1071,
    CODE_AUTHED_DEV_ACK              = 1072,
    CODE_AUTHED_RESULT               = 1073,
    CODE_AUTHED_RESULT_ACK           = 1074,
    CODE_SET_NETWORK_DHCP            = 1101,
    CODE_SET_NETWORK_DHCP_ACK        = 1102,
    CODE_SET_NETWORK_STATIC          = 1103,
    CODE_SET_NETWORK_STATIC_ACK      = 1104,
    CODE_SET_NETWORK_BRIDGE          = 1105,
    CODE_SET_NETWORK_BRIDGE_ACK      = 1106,
    CODE_SET_NETWORK_PPPOE           = 1107,
    CODE_SET_NETWORK_PPPOE_ACK       = 1108,
    CODE_UPGRADE_REPORT              = 1109,
    CODE_UPGRADE_REPORT_ACK          = 1110,
    CODE_SET_BLACKLIST_SWITCH        = 1111,
    CODE_SET_BLACKLIST_SWITCH_ACK    = 1112,
    CODE_TERMINAL_ONLINE_REPORT      = 1140,
    CODE_TERMINAL_ONLINE_REPORT_ACK  = 1141,
    CODE_TERMINAL_OFFLINE_REPORT     = 1142,
    CODE_TERMINAL_OFFLINE_REPORT_ACK = 1143,
} cts_code_t;

typedef enum cts_result {
    RESULT_OK                      = 0,
    RESULT_ID_NOT_MATCH            = -80000,
    RESULT_MAC_NOT_FOUND           = -80001,
    RESULT_QUERY_FAILED            = -10002,
    RESULT_CANNOT_EXECUTE          = -20001,
    RESULT_EXECUTE_FAILED          = -20002,
    RESULT_REPORT_FAILED           = -30001,
    RESULT_PLUGIN_INSTALL_FAILED   = -40005,
    RESULT_PLUGIN_UNINSTALL_FAILED = -40008,
    RESULT_PLUGIN_STOP_FAILED      = -40009,
    RESULT_PLUGIN_RUN_FAILED       = -40010,
} cts_result_t;

typedef enum dns_qtype {
    A          = 1,
    NS         = 2,
    MD         = 3,
    MF         = 4,
    CNAME      = 5,
    SOA        = 6,
    MB         = 7,
    MG         = 8,
    MR         = 9,
    NULL       = 10,
    WKS        = 11,
    RTP        = 12,
    HINFO      = 13,
    MINFO      = 14,
    MX         = 15,
    TXT        = 16,
    RP         = 17,
    AFSDB      = 18,
    SIG        = 24,
    KEY        = 25,
    AAAA       = 28,
    LOC        = 29,
    SRV        = 33,
    NAPTR      = 35,
    CERT       = 37,
    DNAME      = 39,
    OPT        = 41,
    APL        = 42,
    DS         = 43,
    SSHFP      = 44,
    IPSECKEY   = 45,
    RRSIG      = 46,
    NSEC       = 47,
    DNSKEY     = 48,
    DHCID      = 49,
    NSEC3      = 50,
    NSEC3PARAM = 51,
    HIP        = 55,
    CDS        = 59,
    CDNSKEY    = 60,
    OPENPGPKEY = 61,
    HTTPS      = 65,
    SPF        = 99,
    TKEY       = 249,
    TSIG       = 250,
    URI        = 256,
    CAA        = 257,
    TA         = 32768,
    DLV        = 32769,
} dns_qtype_t;

#endif